# General
name: Dvid's World
description: "I write code for <a href='http://doctorondemand.com' target='_blank' >Doctor on Demand</a>."
url: ''

markdown: redcarpet
highlighter: pygments

paginate: 6
permalink: /:categories/:title

tagline:
author :
  name : Dvid Silva
  email : contacto@dvidsilva.com
  github : dvidsilva
  twitter : dvidsilva

# Social share and comments.
disqus-id: dvidsilva
twitter: dvidsilva
github: dvidsilva
google: +DvidSilvaOssa

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
atom_path : /atom.xml
rss_path : /rss.xml


# RSS feed
rss-feed-limit: 10
rss-show-full: "no"

JB :
  version : 0.3.0
  analytics :
    provider : google
    google :
        tracking_id : 'UA-12157650-1'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'


